#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 10 15:36:36 2024

@author: yuan
"""

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

iris = load_iris()
X = iris.data[:,2:]
y = iris.target

tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(X,y)

from sklearn.tree import export_graphviz

f = open("/media/yuan/数据/研究生课件/AI与python/iris_tree.dot", 'w')

export_graphviz(
tree_clf,
out_file=f,
feature_names=iris.feature_names[2:],
class_names=iris.target_names,
rounded=True,
filled=True
)

tree_clf.predict_proba([[5, 1.5]])


from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor(max_depth=2)
tree_reg.fit(X, y)

